#ifndef __CppOscilloscopeMainFrame__
#define __CppOscilloscopeMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "CppOscilloscope.h"

//// end generated include

#include "Config.h"
#include "Data.h"

/** Implementing MainFrame */
class CppOscilloscopeMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void DrawPanelOnPaint( wxPaintEvent& event );
		void DrawPanelOnUpdateUI( wxUpdateUIEvent& event );
		void LoadFileButtonOnButtonClick( wxCommandEvent& event );
		void OperatingModeRadioBoxOnRadioBox( wxCommandEvent& event );
		void DrawStyleRadioBoxOnRadioBox( wxCommandEvent& event );
		void ShowGridCheckboxOnCheckBox( wxCommandEvent& event );
		void BitmapSaveButtonOnButtonClick( wxCommandEvent& event );
		void RefreshTimerOnTimer( wxTimerEvent& event );
	public:
		/** Constructor */
		CppOscilloscopeMainFrame( wxWindow* parent );
	//// end generated class members

	private:
		Config _config;
		Data _currentData, _previousData, _historicData;
};

#endif // __CppOscilloscopeMainFrame__
